version: "3.9"

services:
  db:
    platform: linux/amd64
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
  web:
    # platform: linux/amd64
    build: .
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; python project/manage.py migrate && python project/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
