# Generated by Django 4.1.7 on 2023-03-19 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("training_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerchoice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="training_service.question",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="training_service.question",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="training_service.test",
            ),
        ),
        migrations.AlterField(
            model_name="responsehistory",
            name="answer_choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response_history",
                to="training_service.answerchoice",
            ),
        ),
        migrations.AlterField(
            model_name="responsehistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
