# Generated by Django 4.1.7 on 2023-03-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "training_service",
            "0002_alter_answerchoice_question_alter_comment_question_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="responsehistory",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response_history",
                to="training_service.question",
            ),
            preserve_default=False,
        ),
    ]
